name: Test build

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm ci

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
